import { beforeAll, describe, expect, it } from 'vitest'
import { decodeJwt } from 'jose'
import { createHmac } from 'node:crypto'
import { AuthenticationHelper } from 'amazon-cognito-identity-js'
import { hashPassword, verifyPassword } from '../server/utils/password'
import { createUser, ensureClient, ensurePool, findUser, updateUser } from '../server/utils/models'
import { createOpaqueToken, consumeOpaqueToken, issueTokens, jwks, revokeOpaqueToken, verifyAccessToken } from '../server/utils/tokens'
import { createSrpChallenge, createSrpVerifier, verifySrpResponse } from '../server/utils/srp'
import { callbackAllowed, allowedOrigin } from '../server/utils/config'

beforeAll(() => { process.env.DATABASE_PATH = ':memory:'; process.env.COGNITO_MOCK_MODE = 'permissive'; process.env.PUBLIC_URL = 'http://localhost:3000' })

describe('core store and tokens', () => {
  it('hashes passwords with a unique salt', () => {
    const first = hashPassword('Password123!'); const second = hashPassword('Password123!')
    expect(first).not.toBe(second); expect(verifyPassword('Password123!', first)).toBe(true); expect(verifyPassword('bad', first)).toBe(false)
  })

  it('auto provisions pools and clients', () => {
    const pool = ensurePool('ap-northeast-1_example')
    const client = ensureClient('example-client', pool.id)
    expect(client.pool_id).toBe(pool.id)
  })

  it('enforces strict mode for unknown resources', () => {
    process.env.COGNITO_MOCK_MODE = 'strict'
    expect(() => ensurePool('ap-northeast-1_unknown-strict')).toThrowError('User pool does not exist.')
    process.env.COGNITO_MOCK_MODE = 'permissive'
  })

  it('allows loopback origins and configured callback hosts', () => {
    process.env.ALLOWED_ORIGINS = 'https://frontend.example.test'
    process.env.ALLOWED_CALLBACK_HOSTS = 'callback.example.test'
    expect(allowedOrigin('http://localhost:9876')).toBe(true)
    expect(allowedOrigin('https://frontend.example.test')).toBe(true)
    expect(allowedOrigin('https://blocked.example.test')).toBe(false)
    expect(callbackAllowed('https://callback.example.test/auth/callback')).toBe(true)
  })

  it('rejects duplicate users and rotates password/SRP material', () => {
    const pool = ensurePool('ap-northeast-1_users')
    const user = createUser(pool.id, 'rotate@example.com', 'Password123!', {}, 'CONFIRMED')
    expect(() => createUser(pool.id, user.username, 'Password123!')).toThrowError('already exists')
    const oldVerifier = user.srp_verifier
    const updated = updateUser(user.id, { password: 'ChangedPassword123!' })
    expect(updated.srp_verifier).not.toBe(oldVerifier)
    expect(verifyPassword('ChangedPassword123!', updated.password_hash)).toBe(true)
  })

  it('persists users and issues cognito-shaped JWTs', async () => {
    const pool = ensurePool('ap-northeast-1_tokens'); const client = ensureClient('token-client', pool.id)
    const user = createUser(pool.id, 'dev@example.com', 'Password123!', { email: 'dev@example.com', email_verified: 'true' }, 'CONFIRMED')
    expect(findUser(pool.id, 'dev@example.com')?.id).toBe(user.id)
    const tokens = await issueTokens(undefined, pool.id, client.id, user.id, ['openid', 'email'])
    expect(decodeJwt(tokens.IdToken).token_use).toBe('id')
    expect(decodeJwt(tokens.AccessToken).client_id).toBe(client.id)
    expect((await jwks(pool.id)).keys[0]?.alg).toBe('RS256')
    expect((await verifyAccessToken(tokens.AccessToken)).sub).toBe(user.id)
    const jwtParts = tokens.AccessToken.split('.')
    jwtParts[2] = `${jwtParts[2]![0] === 'a' ? 'b' : 'a'}${jwtParts[2]!.slice(1)}`
    await expect(verifyAccessToken(jwtParts.join('.'))).rejects.toThrow('Invalid or expired access token')
  })

  it('consumes authorization codes once and revokes refresh-like tokens', () => {
    const pool = ensurePool('ap-northeast-1_opaque'); const client = ensureClient('opaque-client', pool.id)
    const user = createUser(pool.id, 'opaque@example.com', 'Password123!', {}, 'CONFIRMED')
    const authorizationCode = createOpaqueToken('authorization_code', pool.id, client.id, user.id)
    expect(consumeOpaqueToken(authorizationCode, 'authorization_code').user_id).toBe(user.id)
    expect(() => consumeOpaqueToken(authorizationCode, 'authorization_code')).toThrowError('Invalid or expired authorization_code')
    const opaque = createOpaqueToken('session', pool.id, client.id, user.id)
    expect(consumeOpaqueToken(opaque, 'session').user_id).toBe(user.id)
    revokeOpaqueToken(opaque)
    expect(() => consumeOpaqueToken(opaque, 'session')).toThrowError('Invalid or expired session')
  })

  it('validates proofs generated by the Cognito JavaScript SRP client', async () => {
    const poolId = 'ap-northeast-1_srpclient'
    const poolName = 'srpclient'
    const username = 'srp@example.com'
    const password = 'Password123!'
    const verifier = createSrpVerifier(poolId, username, password)
    const challenge = createSrpChallenge(verifier.verifier)
    const helper = new AuthenticationHelper(poolName) as any
    const BigInteger = helper.N.constructor
    const A = await new Promise<any>((resolve, reject) => helper.getLargeAValue((error: Error | null, value: unknown) => error ? reject(error) : resolve(value)))
    const key = await new Promise<Buffer>((resolve, reject) => helper.getPasswordAuthenticationKey(username, password, new BigInteger(challenge.B, 16), new BigInteger(verifier.salt, 16), (error: Error | null, value: Buffer) => error ? reject(error) : resolve(value)))
    const timestamp = 'Tue Jul 14 23:00:00 UTC 2026'
    const message = Buffer.concat([Buffer.from(poolName), Buffer.from(username), Buffer.from(challenge.secretBlock, 'base64'), Buffer.from(timestamp)])
    const signature = createHmac('sha256', key).update(message).digest('base64')
    expect(verifySrpResponse({ poolId, username, verifier: verifier.verifier, b: challenge.b, B: challenge.B, A: A.toString(16), secretBlock: challenge.secretBlock, timestamp, signature })).toBe(true)
  })
})
